version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nodejs-backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    container_name: nginx-frontend
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
